### ISSUE TITLE
Can you write simple document ?

### ISSUE THREAD

**Issue by NantipatSoftEn** [tspn/nginx-upstream-response-time-measurement#1]
If you have time.  Can you write simple document ?
I will fork for test my project streaming. 
Thx. 🦄

**Comment by tnuanchuay** [comment]
This repository's objective is to find out the best way to gather and extract Nginx's log messages.
Mainly Idea is adapting ELK stack.

I am not sure this repository will fit to all other project/solution. I would prefer you to look into what's ELK stack and then make compare/conclusion that it will be useful or not.

**Comment by NantipatSoftEn** [comment]
OK never mind.
